In [7]:
import pandas as pd

In [8]:
df_meta = pd.read_csv('Conta-Ecos-Progressivos-Campanhas-01_11_2025-30_11_2025.csv')

display (df_meta)

,Início dos relatórios,Fim dos relatórios,Nome da campanha,Apresentação de campanhas,Resultados,Indicador de resultados,Custo por resultados,Orçamento dos conjuntos de anúncios,Tipo de orçamento do conjunto de anúncios,Montante gasto (EUR),Impressões,Alcance,Termina a,Definição de atribuição,Resultados (iniciais),Indicador de resultados (inicial)
0,2025-11-01,2025-11-30,Ecos Progressivos - conversões nov25,completed,7,actions:offsite_conversion.custom.137071381133...,9.255714,65,Toda a duração,64.79,25386,16338,2025-11-25,"Clique com 7 dias, visualização com 1 dia ou v...",NaN,NaN

In [9]:
campanha = df_meta[df_meta['Nome da campanha'] == 'Ecos Progressivos - conversões nov25']

impressoes = float(campanha['Impressões'].values[0])
alcance = float(campanha['Alcance'].values[0])
custo = float(campanha['Montante gasto (EUR)'].values[0])

In [10]:
df_mail = pd.read_csv('subscribed_email_audience_export_fc258fbd07.csv')

display (df_mail)

,Endereço de e-mail,MEMBER_RATING,OPTIN_TIME,OPTIN_IP,CONFIRM_TIME,CONFIRM_IP,GMTOFF,DSTOFF,TIMEZONE,CC,REGION,LAST_CHANGED,LEID,EUID,NOTES,TAGS
0,lmds@outlook.pt,2,2025-11-15 11:55:37,3.93.195.218,2025-11-15 11:55:37,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-15 11:55:37,42334,be6d6a7ce4,NaN,NaN
1,josecarvalho690@gmail.com,2,2025-11-23 07:58:50,54.87.138.217,2025-11-23 07:58:50,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-23 07:58:50,43096,26965498e1,NaN,NaN
2,ok.tinto@gmail.com,2,2025-11-22 12:47:18,3.93.195.218,2025-11-22 12:47:18,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-22 12:47:18,43092,aa76582cca,NaN,NaN
3,noriekim@gmail.com,2,2025-11-12 13:32:51,3.93.195.218,2025-11-12 13:32:51,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-12 13:32:51,42323,31420650f5,NaN,NaN
4,kilbonitz@gmail.com,2,2025-11-22 07:01:16,3.93.195.218,2025-11-22 07:01:16,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-22 07:01:16,43091,1a1fffb7dd,NaN,NaN
5,aureliano.vasconcelos@gmail.com,2,2025-11-24 18:02:56,54.87.138.217,2025-11-24 18:02:56,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-24 18:02:56,43098,a9e9aa0caf,NaN,NaN
6,madman64@live.com.pt,2,2025-11-22 06:24:30,98.80.211.14,2025-11-22 06:24:30,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-22 06:24:31,43090,a99fdee18b,NaN,NaN
7,vasco1000hs@gmail.com,2,2025-11-15 04:40:10,54.87.138.217,2025-11-15 04:40:10,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-15 04:40:10,42333,1e3f89f9e1,NaN,NaN
8,pauloavferreira@gmail.com,2,2025-11-15 15:24:13,54.87.138.217,2025-11-15 15:24:13,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-15 15:24:13,42335,6dc2310ce8,NaN,NaN
9,jpmpa1965@gmail.com,2,2025-11-13 04:22:58,3.93.195.218,2025-11-13 04:22:58,NaN,NaN,NaN,europe/lisbon,pt,11.0,2025-11-13 04:22:58,42326,9cd7259737,NaN,NaN
10,ruipedrosa@hotmail.com,2,2025-11-12 23:45:52,34.227.47.155,2025-11-12 23:45:52,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-12 23:45:52,42324,0385b721d9,NaN,NaN
11,ricardojorgefmarques@gmail.com,2,2025-11-20 07:11:40,98.80.211.14,2025-11-20 07:11:40,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-20 07:11:40,42348,55fa3ef273,NaN,NaN
12,jolriao@gmail.com,2,2025-11-24 03:24:28,54.87.138.217,2025-11-24 03:24:28,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-24 03:24:28,43097,739d55bf04,NaN,NaN
13,joaquimfarias@gmail.com,2,2025-11-22 13:20:49,18.209.171.63,2025-11-22 13:20:49,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-22 13:20:49,43093,a67da50982,NaN,NaN
14,jsousa2002@gmail.com,2,2025-11-15 20:51:07,100.24.47.195,2025-11-15 20:51:07,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-15 20:51:07,42337,1b2cbca2ae,NaN,NaN
15,jeronimo.ius@gmail.com,2,2025-11-15 19:02:55,54.87.138.217,2025-11-15 19:02:55,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-15 19:02:55,42336,d3d93dcc3e,NaN,NaN

In [11]:
subscricoes = float(len(df_mail))

In [12]:
df_ga4 = pd.read_csv('Resumo_dos_relatórios.csv', skiprows=243, nrows=6)

In [13]:
display (df_ga4)

    Nome do evento  Contagem de eventos
0        page_view                  614
1    session_start                  532
2      first_visit                  481
3           scroll                  122
4  user_engagement                  111
5       form_start                   43

In [14]:
visitas = float (df_ga4.loc[df_ga4['Nome do evento'] == 'first_visit', 'Contagem de eventos'].values[0])
scrolls = float(df_ga4.loc[df_ga4['Nome do evento'] == 'scroll', 'Contagem de eventos'].values[0])
inicios_form = float(df_ga4.loc[df_ga4['Nome do evento'] == 'form_start', 'Contagem de eventos'].values[0])

#Transformação

In [15]:
dados_finais = {
    'data_registo': ['2025-11-30'] * 7,
    'plataforma': ['Meta Ads', 'Meta Ads', 'Meta Ads', 'GA4', 'GA4', 'GA4', 'Mailchimp'],
    'metrica': ['Impressoes', 'Alcance', 'Custo_Euros', 'Visitas_Totais', 'Eventos_Scroll', 'Iniciaram_Formulario', 'Subscricoes_Finais'],
    'valor': [impressoes, alcance, custo, visitas, scrolls, inicios_form, subscricoes]
}

df_etl = pd.DataFrame(dados_finais)

In [16]:
print(df_etl.to_string(index=False))

data_registo plataforma              metrica    valor
  2025-11-30   Meta Ads           Impressoes 25386.00
  2025-11-30   Meta Ads              Alcance 16338.00
  2025-11-30   Meta Ads          Custo_Euros    64.79
  2025-11-30        GA4       Visitas_Totais   481.00
  2025-11-30        GA4       Eventos_Scroll   122.00
  2025-11-30        GA4 Iniciaram_Formulario    43.00
  2025-11-30  Mailchimp   Subscricoes_Finais    16.00

In [17]:
!pip install sqlalchemy pyodbc

Requirement already satisfied: sqlalchemy in c:\users\fmcoe\downloads\python\lib\site-packages (2.0.43)
Requirement already satisfied: pyodbc in c:\users\fmcoe\downloads\python\lib\site-packages (5.3.0)
Requirement already satisfied: greenlet>=1 in c:\users\fmcoe\downloads\python\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\fmcoe\downloads\python\lib\site-packages (from sqlalchemy) (4.15.0)

In [18]:
import urllib
from sqlalchemy import create_engine

In [19]:
servidor = 'DESKTOP-9RHK5JJ\\SQLEXPRESS'
base_dados = 'EcosProgressivos'

In [20]:
parametros_conexao = f"DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={servidor};DATABASE={base_dados};Trusted_Connection=yes;"

In [21]:
conexao_codificada = urllib.parse.quote_plus(parametros_conexao)
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={conexao_codificada}")

In [22]:
df_etl.to_sql(
        name='performance_marketing',  # O nome da tabela que criaste no SQL Server
        con=engine,                    # A ponte de ligação
        if_exists='append',            # Se a tabela já existir, adiciona as novas linhas no final
        index=False                    # Ignora a coluna de numeração do Pandas
    )

C:\Users\fmcoe\Downloads\Python\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

7